---
  all:
    children:
      webservers:
        hosts:
          host1:
            ansible_host: <IPAddress>
          host2:
            ansible_host: <IPAddress>      
          host3:
            ansible_host: <IPAddress>    
      control:
        hosts:
          local:
            ansible_connection: local
